name: pokedex
description: "The simpliest pokedex"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed: ^2.4.6
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.6

  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  envied: ^0.5.3

  dio: ^5.4.0

  google_fonts: ^6.1.0

  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.4.6
  build_runner: ^2.4.8

  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.8

  husky: ^0.1.7

  riverpod_generator: ^2.3.10

  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.3
  cached_network_image: ^3.3.1

flutter:

  uses-material-design: true
  #generate: true
  assets:
    - env